#!/bin/bash

if [ "$#" -ne 1 ];then
	echo "ERROR: WRONG NUMBER OF ARGUMENTS"
	exit -1
fi

IFS=$'\n'

DIRECTS=$(find ./ -mindepth 1  -maxdepth 1 ! -name *.git* -type d)

printf "#include \"header.h\"\n\n" > $1
printf "int	main(int argc, char **argv)\n" >> $1
printf "{\n" >> $1
printf "	t_unit	*lst;\n\n" >> $1
for direct in $DIRECTS; do
	PROTOS=$(find $direct -maxdepth 1 -name '00_*.c' -exec grep {} -e"^int.*(void)$" \;)
	PROCESSED=$(echo $PROTOS | rev | cut -c7- | rev | sed -E 's/^int[[:space:]]*//')
	printf "\tloadlaunch(&lst, \"$PROCESSED\", $PROCESSED);\n" >> $1
done
printf "\tactivate_launcher(&lst, argc, argv);\n" >> $1
printf "\treturn (0); \n" >> $1
printf "}\n" >> $1
