#!/bin/bash

if [ "$#" -ne 0 ];then
	echo "ERROR: WRONG NUMBER OF ARGUMENTS"
	exit -1
fi

IFS=$'\n'

DIRECTS=$(find ./ -mindepth 1  -maxdepth 1 ! -name *.git* -type d)

printf "#include \"header.h\"\n\n"
printf "int	main(int argc, char **argv)\n"
printf "{\n"
printf "	t_unit	*lst;\n\n"
for direct in $DIRECTS; do
	PROTOS=$(find $direct -maxdepth 1 -name '00_*.c' -exec grep {} -e"^int.*(void)$" \;)
	PROCESSED=$(echo $PROTOS | rev | cut -c7- | rev | sed -E 's/^int[[:space:]]*//')
	printf "\tloadlaunch(&lst, \"$PROCESSED\", $PROCESSED);\n"
done
printf "\tactivate_launcher(&lst, argc, argv);\n"
printf "\treturn (0); \n"
printf "}\n"

